In [4]:
import numpy as np
# Create a array of odd number from 1 to 50 using a for comprehension and create a numpy array.

In [5]:
arr = [x for x in range(50) if x%2==1]
narr = np.array(arr)

In [7]:
# Find what is the size of ndarray and then create a array of zero number of same size.

25

In [8]:
s = narr.size
zarr = np.zeros(s)

In [ ]:
# Find the 5th last element in narr and set last 5 elements of zarr to that  number.

In [11]:
n = narr[-5]
zarr[-5:]= n
zarr

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  41.,  41.,
        41.,  41.,  41.])

In [ ]:
# Make the odd array into even array by transforming each element to next element.

In [14]:
narr = narr + 1
narr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
# Make all number which are greater than 40 to be 50.

In [17]:
narr[narr >= 40] = 50
narr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 50, 50, 50, 50, 50, 50])

In [20]:
# Get all the elements which belong to every 5th position i.e has index 0,5,10 etc
barr = np.array(['Y','N','N','N','N']*5)
narr[barr=='Y']

array([ 2, 12, 22, 32, 50])

In [21]:
# Resize narr and zarr into 5x5
narr.resize((5,5))
zarr.resize((5,5))

In [22]:
narr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 50],
       [50, 50, 50, 50, 50]])

In [23]:
# Get the same elements as you got above.
narr[:,0]

array([ 2, 12, 22, 32, 50])

In [25]:
# Convert zarr to a 5x5 containing which contains all 0 in 0th row, all 1 in 1st row.
for i in range(5):
    zarr[i] = i
zarr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [34]:
# Get all elements from narr only if element in zarr is even. For odd put -1
newarr = np.where(zarr%2==0, narr, -1)
newarr

array([[ 2,  4,  6,  8, 10],
       [-1, -1, -1, -1, -1],
       [22, 24, 26, 28, 30],
       [-1, -1, -1, -1, -1],
       [50, 50, 50, 50, 50]])

In [44]:
# Find the sum of number only if they are positive and are greater than 25 in narr
newarr[(newarr > 25)].sum()

334