## Creating ndarrays

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [9]:
print('---'*10)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print('---'*10)
print('number of dimension are : {0} '.format(arr2.ndim))
print('---'*10)
print('Shape : {0} '.format(arr2.shape))

------------------------------
[[1 2 3 4]
 [5 6 7 8]]
------------------------------
number of dimension are : 2 
------------------------------
Shape : (2, 4) 


In [7]:
np.zeros(10)                       # array([ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
np.zeros((3, 6)) 
np.arange(15)                      # array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
np.empty((2,3,2))

array([[[  0.00000000e+000,  -3.10503637e+231],
        [  2.15936126e-314,   2.15916019e-314],
        [  2.15919137e-314,   2.15916076e-314]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  2.13637090e-314,   6.36598737e-311],
        [  0.00000000e+000,   8.34402831e-309]]])

## Data Types for ndarrays

In [8]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
### Chaning the data type ###
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)              # Created in-place changes.

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

## Operations between Arrays and Scalars (Vectorization)

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr1 = arr + arr 
print(arr1)
print('---'*10)
arr * 5                           # Is'nt in-place changes.

[[  2.   4.   6.]
 [  8.  10.  12.]]
------------------------------


array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

## Basic Indexing and Slicing

In [14]:
arr = np.arange(10)              #  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[5]                           #  5
arr[5:8]                         #  array([5, 6, 7])
arr[5:8] = 12                    # Slices are just views. So they do in-place changes.
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]                         # array([7, 8, 9])
arr2d[0][2]                      # is same as 
arr2d[0, 2]                      # 3
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]                         # array([[1, 2, 3],[4, 5, 6]])
arr3d[1, 0]

array([7, 8, 9])

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

## Boolean Indexing

In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape((7,4))
names == 'bob'                    # array([ True, False, False, True, False, False, False], dtype=bool)
print(data[names == 'Bob'])
print('---'*10)
print(data[names == 'Bob', 2:])

[[ 0  1  2  3]
 [12 13 14 15]]
------------------------------
[[ 2  3]
 [14 15]]


In [23]:
data[data < 14] = 0
data

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

## Fancy Indexing - Indexing using Intergers

In [25]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr[[4, 3, 0, 6]])
print('---'*10)
print(arr[[-3, -5, -7]])
print('---'*10)
arr1 = np.arange(32).reshape((8, 4))
arr1[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 6.  6.  6.  6.]]
------------------------------
[[ 5.  5.  5.  5.]
 [ 3.  3.  3.  3.]
 [ 1.  1.  1.  1.]]
------------------------------


array([ 4, 23, 29, 10])

## Transposing Arrays and Swapping Axes

In [27]:
arr = np.arange(4).reshape((2,2))
print(arr.T)
print('---'*10)
np.dot(arr.T,arr)

[[0 2]
 [1 3]]
------------------------------


array([[ 4,  6],
       [ 6, 10]])

## Universal Functions: Fast Element-wise Array Functions

In [28]:
arr = np.arange(10)
print(np.sqrt(arr))
print('---'*10)
np.maximum(arr, arr+2)                    # element-wise maximum

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
------------------------------


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Expressing Conditional Logic as Array Operations

In [31]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
# result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result = np.where(cond, xarr, yarr)
print(result)
print('---'*10)
arr = np.random.randn(4, 4)                     # normally-distributed data
print(arr)
print('---'*10)
print(np.where(arr > 0, 2, -2))
print('---'*10)
print(np.where(arr > 0, 2, arr))

[ 1.1  2.2  1.3  1.4  2.5]
------------------------------
[[-1.36654007  0.58047584  0.35921066 -0.29119149]
 [ 0.62195525 -0.08719602 -2.92453013 -0.62353334]
 [-0.55910383 -0.56376276  0.16553103 -0.81198557]
 [-1.49893089 -1.26069642  0.2000412  -0.11065819]]
------------------------------
[[-2  2  2 -2]
 [ 2 -2 -2 -2]
 [-2 -2  2 -2]
 [-2 -2  2 -2]]
------------------------------
[[-1.36654007  2.          2.         -0.29119149]
 [ 2.         -0.08719602 -2.92453013 -0.62353334]
 [-0.55910383 -0.56376276  2.         -0.81198557]
 [-1.49893089 -1.26069642  2.         -0.11065819]]


## Mathematical and Statistical Methods

In [32]:
arr = np.random.randn(5, 4) 
print(arr.mean())
print('---'*10)
print(arr.sum())
print('---'*10)
print(arr.mean(axis=1))
print('---'*10)
print(arr.sum(0))

-0.159155367661
------------------------------
-3.18310735323
------------------------------
[-0.01167059  0.14411612 -0.36698484 -0.15404284 -0.40719468]
------------------------------
[-1.99773413  1.83144572 -0.338726   -2.67809294]


## Methods for Boolean Arrays and Sorting

In [33]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

51

In [40]:
arr = np.random.randn(8)
arr.sort()                           
arr = np.random.randn(5, 3)
print(arr)
print('---'*10)
arr.sort(1)
print(arr)

[[ 1.66091512 -0.01888309  0.70579512]
 [ 0.90878386  1.72195252  0.78887233]
 [-0.9891692  -1.89638174 -0.55597144]
 [ 0.67696431  0.89639322  0.24388504]
 [ 0.28649125  0.26409982  1.79125049]]
------------------------------
[[-0.01888309  0.70579512  1.66091512]
 [ 0.78887233  0.90878386  1.72195252]
 [-1.89638174 -0.9891692  -0.55597144]
 [ 0.24388504  0.67696431  0.89639322]
 [ 0.26409982  0.28649125  1.79125049]]


## Unique and Other Set Logic

In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
# sorted(set(names)) in plain python

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)
np.load('some_array.npy')
arr = np.loadtxt('array_ex.txt', delimiter=',')